
export const BLOGS_HOME_FAIL = 'BLOGS_HOME_FAIL'
export const BLOGS_HOME_REQUEST = 'BLOGS_HOME_REQUEST'
export const BLOGS_HOME_SUCCESS = 'BLOGS_HOME_SUCCESS'

export const BLOGS_ALL_FAIL = 'BLOGS_ALL_FAIL'
export const BLOGS_ALL_REQUEST = 'BLOGS_ALL_REQUEST'
export const BLOGS_ALL_SUCCESS = 'BLOGS_ALL_SUCCESS'
export const BLOG_READ_CLEAN_STATE = 'BLOG_READ_CLEAN_STATE'

export const BLOGS_SEARCH_REQUEST = 'BLOGS_SEARCH_REQUEST'
export const BLOGS_SEARCH_SUCCESS = 'BLOGS_SEARCH_SUCCESS'
export const BLOGS_SEARCH_FAIL = 'BLOGS_SEARCH_FAIL'
export const BLOGS_SEARCH_EXIT = 'BLOGS_SEARCH_EXIT'

export const BLOG_READ_REQUEST = 'BLOG_READ_REQUEST'
export const BLOG_READ_SUCCESS = 'BLOG_READ_SUCCESS'
export const BLOG_READ_ERROR = 'BLOG_READ_SUCCESS'
export const BLOG_READ_DESTROY_ERROR = 'BLOG_READ_DESTROY_ERROR'

export const BLOG_PUBLISH_REQUEST = 'BLOG_PUBLISH_REQUEST'
export const BLOG_PUBLISH_SUCCESS = 'BLOG_PUBLISH_SUCCESS'
export const BLOG_PUBLISH_ERROR = 'BLOG_PUBLISH_ERROR'

export const BLOG_DELETE_REQUEST = 'BLOG_DELETE_REQUEST'
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS'
export const BLOG_DELETE_ERROR = 'BLOG_DELETE_ERROR'

export const BLOG_APPLAUD_REQUEST = 'BLOG_APPLAUD_REQUEST'
export const BLOG_APPLAUD_SUCCESS = 'BLOG_APPLAUD_SUCCESS'
export const BLOG_APPLAUD_ERROR = 'BLOG_APPLAUD_ERROR'

export const BLOG_CREATE_REQUEST = 'BLOG_CREATE_REQUEST'
export const BLOG_CREATE_SUCCESS = 'BLOG_CREATE_SUCCESS'
export const BLOG_CREATE_FAIL = 'BLOG_CREATE_FAIL'
export const BLOG_CREATE_DESTROY_ERROR = 'BLOG_CREATE_DESTROY_ERROR'
export const BLOG_CREATE_CLEAN_STATE = 'BLOG_CREATE_CLEAN_STATE'
export const BLOG_SAVE_SUCCESS = 'BLOG_SAVE_SUCCESS'
export const BLOG_SAVE_IDLE = 'BLOG_SAVE_IDLE'

export const BLOG_UPDATE_REQUEST = 'BLOG_UPDATE_REQUEST'
export const BLOG_UPDATE_SUCCESS = 'BLOG_UPDATE_SUCCESS'
export const BLOG_UPDATE_FAIL = 'BLOG_UPDATE_FAIL'
export const BLOG_UPDATE_DESTROY_ERROR = 'BLOG_UPDATE_DESTROY_ERROR'
