
export const CONTACT_SUBMIT_REQUEST = 'CONTACT_SUBMIT_REQUEST'
export const CONTACT_SUBMIT_FAIL = 'CONTACT_SUBMIT_FAIL'
export const CONTACT_SUBMIT_SUCCESS = 'CONTACT_SUBMIT_SUCCESS'
export const CONTACT_SUBMIT_DESTROY_ERROR = 'CONTACT_SUBMIT_DESTROY_ERROR'