
export const RESUME_DOWNLOAD_REQUEST = 'RESUME_DOWNLOAD_REQUEST'
export const RESUME_DOWNLOAD_SUCCESS = 'RESUME_DOWNLOAD_SUCCESS'
export const RESUME_DOWNLOAD_FAIL = 'RESUME_DOWNLOAD_FAIL'
export const RESUME_DOWNLOAD_DESTROY_ERROR = 'RESUME_DOWNLOAD_DESTROY_ERROR'